version: '3.8'
services:
  
  dashboard:
    build:
      context: .
      dockerfile: Dashboard/Dockerfile.Dashboard
    image: daq-dashboard:latest
    container_name: dashboard
    volumes:
      - ./config.env:/app/config.env
      - /dev/bus/usb:/dev/bus/usb
    devices:
      - /dev/bus/usb:/dev/bus/usb
    group_add:
      - "${DOCKER_GROUP_ID:-991}"
    ports:
      - "80:80"
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  app-network:
    driver: bridge